modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="pan"
version="${file.jarVersion}"
displayName="PanTheMod_"
logoFile="examplemod.png"
credits="Sub with Prime Gaming"
authors="Made by #1 Mod ShaLiin_"
description='''

Mod made for PanTheMan_ on twitch

PS: Sub with Prime Gaming
'''

